// <auto-generated />
using System;
using ManajemenRuangan.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _2026_manajemenruangan_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215031715_UpdateRoomSeedData")]
    partial class UpdateRoomSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ManajemenRuangan.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Location = "C305",
                            Name = "Lab Jaringan Komputer"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            Location = "C105",
                            Name = "Lab Database"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Location = "C206",
                            Name = "Lab Agile"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 60,
                            Location = "A201",
                            Name = "Ruangan Kelas A201"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 60,
                            Location = "A202",
                            Name = "Ruangan Kelas A202"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 60,
                            Location = "A203",
                            Name = "Ruangan Kelas A203"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 60,
                            Location = "A204",
                            Name = "Ruangan Kelas A204"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 60,
                            Location = "A205",
                            Name = "Ruangan Kelas A205"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 75,
                            Location = "A301",
                            Name = "Ruangan Kelas A301"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 75,
                            Location = "A302",
                            Name = "Ruangan Kelas A302"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 60,
                            Location = "A303",
                            Name = "Ruangan Kelas A303"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 60,
                            Location = "A304",
                            Name = "Ruangan Kelas A304"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 60,
                            Location = "A305",
                            Name = "Ruangan Kelas A305"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 400,
                            Location = "Gedung Student Center",
                            Name = "Student Center"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 200,
                            Location = "Masjid An Nahl",
                            Name = "Masjid An-Nahl"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 300,
                            Location = "Lapangan Merah",
                            Name = "Lapangan Merah"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 60,
                            Location = "Gedung D3",
                            Name = "Perpustakaan D3"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 60,
                            Location = "Gedung Pasca Sarjana",
                            Name = "Perpustakaan Pasca Sarjana"
                        });
                });

            modelBuilder.Entity("ManajemenRuangan.Api.Models.RoomBorrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tujuan")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomBorrowings");
                });

            modelBuilder.Entity("ManajemenRuangan.Api.Models.RoomBorrowing", b =>
                {
                    b.HasOne("ManajemenRuangan.Api.Models.Room", "Room")
                        .WithMany("RoomBorrowings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ManajemenRuangan.Api.Models.Room", b =>
                {
                    b.Navigation("RoomBorrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
